config/routes.rb
class Subdomain
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != 'www'
  end
end

Bookthatapp::Application.routes.draw do
  root :to => 'home#index'

  mount StripeEvent::Engine => '/stripe' # gem 'stripe-event'

  devise_for :users, controllers: {
      sessions: 'users/sessions', registrations: "users/registrations"
  }

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  scope '/hooks' do
    post 'app/uninstalled'     => 'hooks#uninstall'
    post 'orders/create'       => 'hooks#order'
    post 'orders/paid'         => 'hooks#paid'
    post 'orders/cancelled'    => 'hooks#cancelled'
    post 'orders/update'       => 'hooks#orders_update'
    post 'products/update'     => 'hooks#update'
    post 'products/delete'     => 'hooks#delete'
    post 'mail'                => 'hooks#mail'
  end

  scope '/apps' do
    get 'bookthatapp(/:action(/:id))', :controller => 'proxy'
  end

  resources :accounts

  get '/navigate(/:action(/:id))', :controller => 'navigate'

  constraints(Subdomain) do
    resources :resource_groups, :users, :product_imports, :events, :blackouts, :locations

    resources :shops do
      member do
        get 'locations'
      end
    end

    resources :resources do
      resources :schedules
    end

    scope ':calendar' do
      # get '', to: 'calendar#index'
    end

    resources :bookings do
      member do
        get 'ticket'
        get 'email_activity'
        post 'attendance', :constraints => {:format => /(json)/}
      end
    end

    resources :products do
      resources :reservations
      resources :waitlists
      resources :variants do
        post 'reset', :on => :collection
      end

      collection do
        get 'autocomplete'
      end
      resources :terms, except: [:index]
    end

    resource :availabilities, only: [:index], defaults: { format: 'json' } do
      collection do
        get 'capacity'
        get 'preview'
        get 'schedule'
      end
    end

    resources :templates do
      get 'new_reminder', :on => :collection
    end

    resource :feedback, only: [:new, :create]
    resource :embed, only: [:new, :create]

    mount Knock::Engine => "/api"

    namespace :api do
      namespace :v1 do
        get 'availability' => 'availability#index'
        resources :bookings, only: [:index, :show]
      end

      namespace :v2 do 
        get 'products' => 'products#index'
        get 'product/(id/:id/(availability))' => 'products#get'
        get 'product/variant/:id/capacity' => 'products#getCapacity'
        get 'availability(/ids/:ids)(/from/:from)(/to/:to)' => 'availability#check'
        post 'reserve' => 'reservations#save'
      end
    end

    post 'bookings/reminder(/:id)' => 'bookings#reminder', :as => :reminder
    post 'bookings/sms(/:id)' => 'bookings#sms', :as => :sms
    post 'bookings/send_reminders' => 'bookings#send_reminders', :as => :send_reminders
    get 'charges/confirm'      => 'charges#confirm'
    get 'charges/install'      => 'charges#install'

    get '/auth/:provider/callback' => 'sessions#create'
    get '/signout' => 'sessions#destroy', :as => :signout
    get '/shop/install' => 'shops#install'

    post 'charges/cancelled(/:id)' => 'charges#cancelled', :as => :cancel_installation
    post 'charges/cancel_pending(/:id)' => 'charges#cancel_pending', :as => :cancel_pending_charge
    get 'reports/runsheet'      => 'reports#runsheet', :as => :runsheet
    get 'reports/enrollments'   => 'reports#enrollments', :as => :enrollments
    get '/tests/:action', :controller => 'tests'

    match '/:controller(/:action(/:id))', via: [:get, :post, :patch]
  end

  get 'status' => 'home#status'
  get '/404' => 'errors#error_404'
  get '/422' => 'errors#error_422'
  get '/429' => 'errors#error_429'
  get '/500' => 'errors#error_500'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  get '/:controller(/:action(/:id))'

  # otherwise show not found
  #get ':url' => 'application#not_found', :constraints => { :url => /.*/ }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'brochure'

  def index
    current_host = "#{request.host}#{':' + request.port.to_s if request.port != 80}"
    @callback_url = "http://#{current_host}/login/finalize"
    respond_to :html
  end

  def status
    render :inline => "<h1>Status</h1><p>Good</p>"
  end

  def view
    if params[:shop].present?
      redirect_to :controller => 'Events', :action => "index", :subdomain => params[:shop].split('.')[0]
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/about.html.erb
<div class="header page">
    <h1>About Us</h1>
</div>
<div id="about" class="padding">
    <div class="wrap_image_left">
        <img src="images/about_img.jpg" alt="" />
    </div>
    <p>
        BookThatApp, in conjunction with Shopify, is a your complete Reservation Management System.
    </p>
	<p>
		Aenean diam massa, fringilla quis consectetur et, iaculis id mi. Curabitur turpis risus, pharetra eget pretium id, lobortis sit amet elit. Sed tincidunt lorem orci, vel ultrices libero. Vestibulum convallis pulvinar aliquet. Donec tincidunt adipiscing velit, in commodo leo porta in. Maecenas sollicitudin quam ut ipsum tristique vel sagittis lectus luctus. Cras semper malesuada faucibus. Fusce dapibus condimentum euismod. Etiam lacinia eros elit, vel convallis elit. Cras orci elit, viverra sit amet consequat at, porta id elit. Donec egestas, felis vitae iaculis accumsan, leo justo venenatis dui, eget lacinia arcu augue eget ante. Aenean diam massa, fringilla quis consectetur et, iaculis id mi. Curabitur turpis risus, pharetra eget pretium id, lobortis sit amet elit.
	</p>
    <br/>
    <div class="section_title">
        <h3>Meet The Team</h3>
    </div>
    <!-- Start Team Member -->
    <div class="team member_left">
        <h3>Gavin <span>Lead Developer</span></h3>
        <img src="http://themes.two2twelve.com/site/bizcreative/images/ourteam.jpg" alt="" />
        <p>
            Likes to hazor
        </p>
        <ul>
            <li>
                <a href="">Twitter</a>
            </li>
            <li>
                <a href="">Facebook</a>
            </li>
        </ul>
    </div>
    <!-- End Team Member --><!-- Start Team Member -->
    <div class="team member_right">
        <h3>Christine <span>Lead Designer</span></h3>
        <img src="http://themes.two2twelve.com/site/bizcreative/images/ourteam.jpg" alt="" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <ul>
            <li>
                <a href="">Twitter</a>
            </li>
            <li>
                <a href="">Facebook</a>
            </li>
        </ul>
    </div>
    <!-- End Team Member -->
    <div class="clear">
    </div>
</div>

app/views/home/index.html.erb
<% content_for :head do -%>
	<script type='text/javascript'>
	jQuery(document).ready(function($) {
		$("a.screenshot").fancybox({
			'transitionIn'	:	'elastic',
			'transitionOut'	:	'elastic',
			'speedIn'		:	400,
			'speedOut'		:	400,
			'overlayShow'	:	false
		});

		$(".scrollable").scrollable({ });
	});
	</script>
<% end -%>

<div class="header header_home page">
    <div class="price_tag">
    </div>
    <img src="images/brochure/screenshot.jpg" alt="" class="main_screenshot" />
    <div class="info">
        <h1>Book That!</h1>
        <p>Do you offer products for hire (rental), run courses or want to be able to take reservations for appointments, bookings and activities using products from your <a href="https://www.shopify.com/services/signup?ref=gtck" target="_blank">Shopify</a> store?
          BookThatApp tracks your Shopify orders and maintains a bookings calendar for your products. Our easy to use calendar let's you see at a glance your bookings on a monthly, weekly or daily basis. BookThatApp features real-time
		availability showing what products are available based on the inventory you specify in Shopify.</p>
	<%= link_to login_url(subdomain: "www"), class: "button icon" do %>
	  <img src="images/brochure/go_icon.png" alt="" /><span> Signup Now!</span>
	<% end %>
        <span class="trial">$US <%= Bookthatapp::Application.config.price %>/month -  <%= Bookthatapp::Application.config.trial_period %> day free trial.</span>
    </div>
    <!-- End App Info -->
    <div class="clear">
    </div>
</div>

<div id="home" class="padding">
    <div id="screenshots">
        <div class="section_title">
            <h3>Screenshots</h3>
        </div>
        <a href="javascript:;" class="controls prev">Previous</a>
        <div class="scrollable">
            <div class="items">
                <ul>
                    <li>
                      <a href="images/brochure/screenshots/bta-calendar-full.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/bta-calendar-thumb.jpg" alt="Shopify Booking Calendar" /></a>
                    </li>
                    <li>
                      <a href="images/brochure/screenshots/bta-product.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/bta-product-thumb.jpg" alt="Import products for booking availability" /></a>
                    </li>
                    <li>
                      <a href="images/brochure/screenshots/bta-email.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/bta-email-thumb.jpg" alt="Configure reminder emails" /></a>
                    </li>
                  <li>
                    <a href="images/brochure/screenshots/bta-site-templates.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/bta-site-templates-thumb.jpg" alt="Customize availability search" /></a>
                  </li>
                  <li>
                    <a href="images/brochure/screenshots/bta-tooltip.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/bta-tooltip-thumb.jpg" alt="View booking details at a glance" /></a>
                  </li>
                </ul>
				<!--
                <ul>
                    <li>
                        <a href="images/screenshots/screen_1.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/screen_1_thumb.jpg" alt="" /></a>
                    </li>
                    <li>
                        <a href="images/screenshots/screen_2.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/screen_2_thumb.jpg" alt="" /></a>
                    </li>
                    <li>
                        <a href="images/screenshots/screen_3.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/screen_3_thumb.jpg" alt="" /></a>
                    </li>
                    <li>
                        <a href="images/screenshots/screen_4.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/screen_4_thumb.jpg" alt="" /></a>
                    </li>
                    <li>
                        <a href="images/screenshots/screen_5.jpg" class="screenshot" rel="group"><img src="images/brochure/screenshots/screen_5_thumb.jpg" alt="" /></a>
                    </li>
                </ul> -->
            </div>
        </div><a href="javascript:;" class="controls next">Next</a>
        <div class="clear">
        </div>
    </div>
    <div id="features">
        <div class="section_title">
            <h3>Features &amp; Specs</h3>
        </div>
        <p>
            <b>Shopify Booking Engine</b>
            <img src="images/brochure/shopify-bag-btn-63.png" alt="" />BookThatApp seamlessly integrates with Shopify to keep track of bookings made for your products. When an
          order is placed a booking is automatically created in BookThatApp.
        </p>
        <p>
            <b>Book Anything!</b>
            <img src="images/brochure/icons/track.gif" alt="" />BookThatApp is perfect for stores offering equipment or product rentals, course and class bookings, tours and activities,
          or as an appointment management system.
        </p>
        <p class="last">
            <b>Real-time Bookings &amp; Availability</b>
            <img src="images/brochure/icons/time.gif" alt="" />BookThatApp's reservation management system integrates into your product and cart pages offering availability updates in real time.
        </p>
        <div class="clear spacer">
        </div>
        <p>
            <b>Pending/Confirmed Bookings</b>
            <img src="images/brochure/icons/task.gif" alt="" />BookThatApp can be set up to create reserved bookings for orders where payment is authorized, but not captured. Once a payment is made, the booking becomes confirmed.
        </p>
        <p>
            <b>View by Month, Week or Day</b>
            <img src="images/brochure/icons/schedule.gif" alt="" />View bookings using Day, Week, or Month view. Color coding lets you see at a glance your confirmed and pending bookings.
        </p>
        <p class="last">
            <b>Brought to you by Conciergify</b>
            <img src="images/brochure/icons/dude.gif" alt="" /> <a href="http://www.shopifyconcierge.com">Shopfiy<em>Concierge</em></a> have years of experience developing Shopify themes and apps, and our <a href="http://support.shopifyconcierge.com/home">help desk</a> and dedicated <a href="http://support.shopifyconcierge.com/forums/332501-bookthatapp-shopify-application">support forum</a>
			ensures you get timely and expert help.
        </p>
        <div class="clear">
        </div>
    </div>
</div>