config/routes.rb
class Subdomain
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != 'www'
  end
end

Bookthatapp::Application.routes.draw do
  root :to => 'home#index'

  mount StripeEvent::Engine => '/stripe' # gem 'stripe-event'

  devise_for :users, controllers: {
      sessions: 'users/sessions', registrations: "users/registrations"
  }

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  scope '/hooks' do
    post 'app/uninstalled'     => 'hooks#uninstall'
    post 'orders/create'       => 'hooks#order'
    post 'orders/paid'         => 'hooks#paid'
    post 'orders/cancelled'    => 'hooks#cancelled'
    post 'orders/update'       => 'hooks#orders_update'
    post 'products/update'     => 'hooks#update'
    post 'products/delete'     => 'hooks#delete'
    post 'mail'                => 'hooks#mail'
  end

  scope '/apps' do
    get 'bookthatapp(/:action(/:id))', :controller => 'proxy'
  end

  resources :accounts

  get '/navigate(/:action(/:id))', :controller => 'navigate'

  constraints(Subdomain) do
    resources :resource_groups, :users, :product_imports, :events, :blackouts, :locations

    resources :shops do
      member do
        get 'locations'
      end
    end

    resources :resources do
      resources :schedules
    end

    scope ':calendar' do
      # get '', to: 'calendar#index'
    end

    resources :bookings do
      member do
        get 'ticket'
        get 'email_activity'
        post 'attendance', :constraints => {:format => /(json)/}
      end
    end

    resources :products do
      resources :reservations
      resources :waitlists
      resources :variants do
        post 'reset', :on => :collection
      end

      collection do
        get 'autocomplete'
      end
      resources :terms, except: [:index]
    end

    resource :availabilities, only: [:index], defaults: { format: 'json' } do
      collection do
        get 'capacity'
        get 'preview'
        get 'schedule'
      end
    end

    resources :templates do
      get 'new_reminder', :on => :collection
    end

    resource :feedback, only: [:new, :create]
    resource :embed, only: [:new, :create]

    mount Knock::Engine => "/api"

    namespace :api do
      namespace :v1 do
        get 'availability' => 'availability#index'
        resources :bookings, only: [:index, :show]
      end

      namespace :v2 do 
        get 'products' => 'products#index'
        get 'product/(id/:id/(availability))' => 'products#get'
        get 'product/variant/:id/capacity' => 'products#getCapacity'
        get 'availability(/ids/:ids)(/from/:from)(/to/:to)' => 'availability#check'
        post 'reserve' => 'reservations#save'
      end
    end

    post 'bookings/reminder(/:id)' => 'bookings#reminder', :as => :reminder
    post 'bookings/sms(/:id)' => 'bookings#sms', :as => :sms
    post 'bookings/send_reminders' => 'bookings#send_reminders', :as => :send_reminders
    get 'charges/confirm'      => 'charges#confirm'
    get 'charges/install'      => 'charges#install'

    get '/auth/:provider/callback' => 'sessions#create'
    get '/signout' => 'sessions#destroy', :as => :signout
    get '/shop/install' => 'shops#install'

    post 'charges/cancelled(/:id)' => 'charges#cancelled', :as => :cancel_installation
    post 'charges/cancel_pending(/:id)' => 'charges#cancel_pending', :as => :cancel_pending_charge
    get 'reports/runsheet'      => 'reports#runsheet', :as => :runsheet
    get 'reports/enrollments'   => 'reports#enrollments', :as => :enrollments
    get '/tests/:action', :controller => 'tests'

    match '/:controller(/:action(/:id))', via: [:get, :post, :patch]
  end

  get 'status' => 'home#status'
  get '/404' => 'errors#error_404'
  get '/422' => 'errors#error_422'
  get '/429' => 'errors#error_429'
  get '/500' => 'errors#error_500'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  get '/:controller(/:action(/:id))'

  # otherwise show not found
  #get ':url' => 'application#not_found', :constraints => { :url => /.*/ }
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
    <%= render 'common/error_messages', :object => f.object %>
    <table class="form-table styled">
      <tbody>
      <tr>
        <td class="title">
          <%= f.label :name %>
        </td>
        <td>
          <%= f.text_field :name, required: true %>
        </td>
      </tr>
      <tr>
        <td class="title">
          <%= f.label :description %>
        </td>
        <td>
          <%= f.text_field :description %>
        </td>
      </tr>
      <tr>
        <td class="title">
          <%= f.label :resource_type, 'Type' %>
        </td>
        <td>
          <%= f.select :resource_type, @resource_types, {prompt: "Select Type of Resource"} %>
        </td>
      </tr>

      </tbody>
    </table>

    <div class="tab-footer clear" style="display: block; margin-top: 20px;">
      <div class="button-bar">
        <%= f.submit "Save" %>
        <%= link_to "Close", resources_path %>
      </div>
    </div>
<% end %>

app/views/resources/edit.html.erb
<div class="content-box">
  <div class="box-header clear">
    <h2>Edit Resource</h2>
  </div>
  <div class="box-body clear">
    <%= render 'form' %>
  </div>
</div>

app/views/resources/index.html.erb
<h1>Configuration</h1>
<p>Set up BookThatApp.</p>

<div class="content-box">
  <div class="box-header clear">
    <h2>Resources</h2>
  </div>
  <div class="box-body clear">
    <p><%= link_to 'Add Resource', new_resource_path, class:'submit' %></p>
    <table class="styled">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Type</th>
        <th class="table-actions"></th>
      </tr>

      <% @resources.each do |resource| %>
          <tr>
            <td><%= resource.name %></td>
            <td><%= resource.description %></td>
            <td><%= resource.resource_type %></td>
            <td class="table-actions">
              <%= link_to content_tag(:span, '', :class => "ui-icon ui-icon-trash"), resource, :confirm => 'Are you sure you want to delete this resource?', :class => 'ajax-delete' %>
              <%= link_to content_tag(:span, "", :class => 'ui-icon ui-icon-pencil'), edit_resource_path(resource) %>
            </td>
          </tr>
      <% end %>
      <% if @resources.empty? %>
          <tr>
            <td colspan="4">No resources</td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/resources/new.html.erb
<div class="content-box">
  <div class="box-header clear">
    <h2>Create Resource</h2>
  </div>
  <div class="box-body clear">
    <%= render 'form' %>
  </div>
</div>