config/routes.rb
class Subdomain
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != 'www'
  end
end

Bookthatapp::Application.routes.draw do
  root :to => 'home#index'

  mount StripeEvent::Engine => '/stripe' # gem 'stripe-event'

  devise_for :users, controllers: {
      sessions: 'users/sessions', registrations: "users/registrations"
  }

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  scope '/hooks' do
    post 'app/uninstalled'     => 'hooks#uninstall'
    post 'orders/create'       => 'hooks#order'
    post 'orders/paid'         => 'hooks#paid'
    post 'orders/cancelled'    => 'hooks#cancelled'
    post 'orders/update'       => 'hooks#orders_update'
    post 'products/update'     => 'hooks#update'
    post 'products/delete'     => 'hooks#delete'
    post 'mail'                => 'hooks#mail'
  end

  scope '/apps' do
    get 'bookthatapp(/:action(/:id))', :controller => 'proxy'
  end

  resources :accounts

  get '/navigate(/:action(/:id))', :controller => 'navigate'

  constraints(Subdomain) do
    resources :resource_groups, :users, :product_imports, :events, :blackouts, :locations

    resources :shops do
      member do
        get 'locations'
      end
    end

    resources :resources do
      resources :schedules
    end

    scope ':calendar' do
      # get '', to: 'calendar#index'
    end

    resources :bookings do
      member do
        get 'ticket'
        get 'email_activity'
        post 'attendance', :constraints => {:format => /(json)/}
      end
    end

    resources :products do
      resources :reservations
      resources :waitlists
      resources :variants do
        post 'reset', :on => :collection
      end

      collection do
        get 'autocomplete'
      end
      resources :terms, except: [:index]
    end

    resource :availabilities, only: [:index], defaults: { format: 'json' } do
      collection do
        get 'capacity'
        get 'preview'
        get 'schedule'
      end
    end

    resources :templates do
      get 'new_reminder', :on => :collection
    end

    resource :feedback, only: [:new, :create]
    resource :embed, only: [:new, :create]

    mount Knock::Engine => "/api"

    namespace :api do
      namespace :v1 do
        get 'availability' => 'availability#index'
        resources :bookings, only: [:index, :show]
      end

      namespace :v2 do 
        get 'products' => 'products#index'
        get 'product/(id/:id/(availability))' => 'products#get'
        get 'product/variant/:id/capacity' => 'products#getCapacity'
        get 'availability(/ids/:ids)(/from/:from)(/to/:to)' => 'availability#check'
        post 'reserve' => 'reservations#save'
      end
    end

    post 'bookings/reminder(/:id)' => 'bookings#reminder', :as => :reminder
    post 'bookings/sms(/:id)' => 'bookings#sms', :as => :sms
    post 'bookings/send_reminders' => 'bookings#send_reminders', :as => :send_reminders
    get 'charges/confirm'      => 'charges#confirm'
    get 'charges/install'      => 'charges#install'

    get '/auth/:provider/callback' => 'sessions#create'
    get '/signout' => 'sessions#destroy', :as => :signout
    get '/shop/install' => 'shops#install'

    post 'charges/cancelled(/:id)' => 'charges#cancelled', :as => :cancel_installation
    post 'charges/cancel_pending(/:id)' => 'charges#cancel_pending', :as => :cancel_pending_charge
    get 'reports/runsheet'      => 'reports#runsheet', :as => :runsheet
    get 'reports/enrollments'   => 'reports#enrollments', :as => :enrollments
    get '/tests/:action', :controller => 'tests'

    match '/:controller(/:action(/:id))', via: [:get, :post, :patch]
  end

  get 'status' => 'home#status'
  get '/404' => 'errors#error_404'
  get '/422' => 'errors#error_422'
  get '/429' => 'errors#error_429'
  get '/500' => 'errors#error_500'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  get '/:controller(/:action(/:id))'

  # otherwise show not found
  #get ':url' => 'application#not_found', :constraints => { :url => /.*/ }
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include BookThatAppUtils

  validates_presence_of :site, :subdomain

  # The reason that we use the subdomain as the unique identifier for a Shop, instead of
  # using the ActiveResource site value, is that the site value could change. If a shop were
  # to revoke access to your application and re-install it at a later date, it would get
  # a new password for your app and its site would change. It's subdomain however is
  # immutable and makes a better key for Shops.
  validates_uniqueness_of :subdomain
  validates_exclusion_of :subdomain, :in => %w(admin, www, shopify, conciergify, support, info, help, api, status)

  has_many :events
  has_many :event_dates, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :booking_items # booking destroys these
  has_many :incomplete_bookings, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :variants, through: :products
  has_many :product_imports, dependent: :destroy
  has_many :locations, dependent: :destroy
  accepts_nested_attributes_for :locations, :reject_if => lambda {|n| n[:name].blank? }, :allow_destroy => true
  has_many :templates, dependent: :destroy, :class_name => "LiquidTemplate"
  has_many :shop_notes, dependent: :destroy
  has_many :blackouts, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :resources, dependent: :destroy
  has_many :resource_groups, dependent: :destroy
  has_many :seasons, as: :hourable, dependent: :destroy
  has_many :email_events, inverse_of: :shop, dependent: :destroy
  has_many :reminder_configs, inverse_of: :shop, dependent: :destroy
  accepts_nested_attributes_for :reminder_configs, reject_if: :all_blank, :allow_destroy => true

  before_create :default_settings #, :generate_authentication_token
  after_create :install, :create_default_reminder

  # delegate :appointments, :classes: :products # sti

  def tz
    tz = ActiveSupport::TimeZone.new(timezone)
    if tz.nil?
      Rails.logger.warn "TimeZone for #{subdomain} not found: #{timezone}. Defaulting to UTC."
      tz = ActiveSupport::TimeZone.new('Etc/UTC')
    end
    tz
  end

  def tzinfo
    tz.tzinfo
  end

  def local_time
    tz.now
  end

  def settings=(options)
    unless options.nil?
      old = settings
      self.settings_yaml = OpenStruct.new(
        :wizard => options['wizard'] || 'inactive',
        :quantity_range => options['quantity_range'] || old.quantity_range,
        :message_booked_out => options['message_booked_out'] || old.message_booked_out,
        :message_blacked_out => options['message_blacked_out'] || old.message_blacked_out,
        :message_unscheduled => options['message_unscheduled'] || old.message_unscheduled,
        :message_unavailable => options['message_unavailable'] || old.message_unavailable,
        :message_closed => options['message_closed'] || old.message_closed,
        :df => options['df'] || old.df,
        :region => options['region'] || old.region,
        :theme => options['theme'] || old.theme
      ).to_yaml
    end
  end

  #when you want a shop to get a note about an action, like a successful job, pass in the_message you want them to see.
  # if it's something for a shop to do and is therefore actionable, pass true in is_actionable.
  def notifier(the_message = "",  info_hash = {})
    shopnotes_hash = {:message => the_message, :actionable => info_hash[:actionable], :shop_id => id, :noteable_id => info_hash[:noteable_id], :noteable_type => info_hash[:noteable_type] }
    ActiveSupport::Notifications.instrument("shopnotes.notifier", shopnotes_hash
                                            )
  end

  def settings
    if self.settings_yaml.blank?
      h = Hash.new
      h["wizard"] = "inactive"
      h["quantity_range"] = "no"
      h["message_booked_out"] = "Booked Out"
      h["message_blacked_out"] = "Blacked Out"
      h["message_unscheduled"] = "Unscheduled"
      h["message_unavailable"] = "Unavailable"
      h["message_closed"] = "Closed"
      h["df"] = "mm/dd/yy"
      h["region"] = ""
      h["theme"] = "smoothness"
      h
    else
      YAML::load(self.settings_yaml)
    end
  end

  def settings_json
    ActiveSupport::JSON.encode(settings.marshal_dump).html_safe
  end

  def template(name)
    template = templates.find_by_name(name.to_s.gsub(/[_-]/, ' ').capitalize)

    # if template doesn't exist create it
    unless template
      template = LiquidTemplate.new
      template.name = name.to_s.gsub(/[_-]/, ' ').split.map(&:capitalize).join(' ')
      template.body = File.read("#{Rails.root}/db/templates/#{name}.liquid")
      template.shop = self
      template.save
    end

    template
  end

  def install
    Delayed::Job.enqueue ShopInstallJob.new(id)
  end

  def create_default_reminder
    template = LiquidTemplate.create(
        shop: self,
        body: File.read("#{Rails.root}/db/templates/reminder.liquid"),
        name: 'Booking Reminder',
        category: TemplateCategory::REMINDER,
        channel: TemplateChannel::EMAIL,
        subject: 'Booking Reminder'
    )
    ReminderConfig.create(
        trigger_type: TriggerType::BEFORE_START,
        liquid_template_id: template.id,
        shop: self
    )
  end

  def resync_timezone
    external do
      store = ShopifyAPI::Shop.current
      self.timezone = store.timezone[12..store.timezone.length]
      self.save
    end
  end

  def resync_products
    products.each {|p| p.resync}
  end

  def resync_booking_date_ranges
    bookings.where('events.start > ?', DateTime.now).each do |b|
      minmax = b.booking_items.collect{|bi| [bi.start, bi.finish]}.flatten.minmax
      bookings.find(b.id).sync_booking_dates if minmax[0] != b.start || minmax[1] != b.finish
    end
  end

  def datetime_parser
    DateTimeParser.new(self)
  end

  def lookup_product_availability(start, finish, the_query)
    the_products = products.search_products(the_query)
    # cache key for a shop's products is the count (accounts for inserts/deletes) and updated_at (accounts for changes in capacity)
    product_ids = the_products.map(&:external_id)
    lookup_availability(start,finish, product_ids)
  end

  def lookup_availability(start, finish, product_ids)
    bta_product_ids = products
                      .where(:external_id => product_ids.flatten)
                      .pluck(:id)
    calc = AvailabilityCalculator2.new(self, start, finish, bta_product_ids)
    calc.calculate()

    # cache_key = availability_cache_key(product_ids, start, finish)
    #
    # Rails.cache.fetch(cache_key, :expires_in => Rails.env.production? ? 1.month : 1.minute) do
    #   # new availability calculator uses bta product ids
    #   bta_product_ids = products.where(:external_id => product_ids).pluck(:id)
    #   calc = AvailabilityCalculator2.new(self, start, finish, bta_product_ids)
    #   calc.calculate()
    # end
  end

  # these keys represent anything that can change that would change how availability is calculated - count (accounts for inserts/deletes) and max(updated_at) accounts for edit changes
  def availability_cache_key(product_ids, start, finish)
    products_cache_key = products.where(:external_id => product_ids).pluck_all("COUNT(*)", "MAX(updated_at)").flatten.first.values.map(&:to_i).join('-')
    events_cache_key = events.where(:external_product_id => product_ids + [nil]).pluck_all("COUNT(*)", "MAX(updated_at)").flatten.first.values.map(&:to_i).join('-')
    event_dates_cache_key = event_dates.where(:external_product_id => product_ids + [nil]).where('finish > ? and start < ?', start, finish).pluck_all("COUNT(*)", "MAX(updated_at)").flatten.first.values.map(&:to_i).join('-')
    constraints_cache_key = ResourceConstraint.joins(:resource).where(:resources => {:shop_id => id}).pluck_all("COUNT(*)", "MAX(resource_constraints.updated_at)").flatten.first.values.map(&:to_i).join('-')
    allocations_cache_key = ResourceAllocation.joins(:resource).where(:resources => {:shop_id => id}).pluck_all("COUNT(*)", "MAX(resource_allocations.updated_at)").flatten.first.values.map(&:to_i).join('-')
    cache_key = [self.updated_at, start, finish, product_ids, products_cache_key, events_cache_key, event_dates_cache_key, constraints_cache_key, allocations_cache_key]
  end

  #use this and fix something is mucked up with blank prod ids
  def empty_products_all_blackouts(start, finish)
    newstyle = blackouts.between(start,finish) #
    old = events.old_blackouts(start, finish)
    #does this send double nils? no because each one is different
    newstyle + old
  end

  def generate_shop_calendar_code
    hmac_sha1(subdomain, subdomain + id.to_s)
  end

  def compare_calendar_code(the_code)
    the_code == generate_shop_calendar_code
  end

  def hmac_sha1(data, secret)
    OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha1'), secret.encode("ASCII"), data.encode("ASCII"))
  end

  # product_ids is an array of BTA product ids
  def all_blackouts(start, finish, product_ids = [])
    # TODO: get rid of EventDate
    newstyle = blackouts.includes([:product, :variant]).where('event_dates.finish > ? and event_dates.start < ?', start, finish)
    newstyle = newstyle.where(:product_id => product_ids + [nil]) unless product_ids.empty?

    old = Event.where(:type => "OldBlackout").where(:shop_id => self.id).where('events.finish > ? and events.start < ?', start, finish)
    old = old.includes(:product).where(:product_id => product_ids + [nil]) unless product_ids.empty?

    newstyle.all + old.all
  end

  def has_class_profile_products?
    products.exists?(:profile => 'class')
  end

  def select_date_format
    df = settings.df || 'mm/dd/yy'
    df.sub('mm', '%m').sub('dd', '%d').sub('yy', '%Y')
  end

  def reset_variant_durations
    products.each do |p|
      p.reset_variant_durations
    end
  end

  def external(&block)
    ::NewRelic::Agent.add_custom_attributes(:account => subdomain)
    old_ar_site = ShopifyAPI::Base.site
    begin

app/helpers/reports_helper.rb
module ReportsHelper
  def display_product_search_options
    @product_id = params[:products] || ''

    products = @account.products.order('product_title')

    profile = params[:profile]
    products = products.where("profile = '#{profile}'") if profile.present?

    opts = ['<option value="">Select...</option>']
    products.each do |product|
      opts << "<option value='#{product.id}' #{"selected='selected'" if product.id.to_s == @product_id} data-external-id=#{product.external_id}>#{product.product_title}</option>"
    end
    opts.join(' ').html_safe
  end

  def display_product_variants
    opts = []
    Variant.where(:product_id => @product_id).each do |variant|
      opts << "<option value='#{variant.id}' data-external-id='#{variant.external_id}' #{"selected='selected'" if variant.id.to_s == @the_data.variant_id}>#{variant.title}</option>"
    end
    opts.join(' ').html_safe
  end

  def display_resources
    @resource_id = params[:resources] || ''
    opts = ['<option value="">Select Resource...</option>']
    @available_resources.each do |resource|
      opts << "<option value='#{resource.id}' #{"selected='selected'" if resource.id.to_s == @resource_id}>#{resource.name}</option>"
    end
    opts.join(' ').html_safe
  end

  def all_day_variants_only?(booking)
    booking.booking_items.all?{|bi| bi.variant.all_day != 0}
  end
end

app/views/reports/enrollment.html.erb
<% if @product.blank? || @start.blank? %>
<h4>No Products</h4>
<p>You will need a product, start time to display bookings on this page.</p>
<% else %>
<h4><%= @product.product_title %> - <%= I18n.localize(@start.to_time, :format => :short) %></h4>
<div class="dataTables_wrapper">
<table class="styled">
  <thead>
  <tr>
    <th width="1%">Booking</th>
    <th width="1%">Order</th>
    <th width="1%">Status</th>
    <th class="nowrap">Customer</th>
    <th class="nowrap">Email<span class="no-print ui-icon ui-icon-mail-closed"></span></th>
    <th class="nowrap">Phone</th>
    <th>Notes</th>
    <th width="1%"># in Party</th>
  </tr>
  </thead>
  <tbody>
  <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to booking.id, edit_booking_path(booking) %></td>
        <td>
          <a href='<%= "https://#{current_shop.url}/admin/orders/#{booking.order_id}" %>' target='_blank'>
            <%= booking.order_name.nil? ? "View Order" : booking.order_name %>
          </a>
        </td>
        <td><%= booking.status == 1 ? "Reserved" : "Confirmed" %></td>
        <td><%= booking.name %></td>
        <td><%= mail_to booking.email, booking.email %></td>
        <td><%= booking.phone %></td>
        <td><%= booking.notes %></td>
        <td><%= booking.number_in_party %></td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td colspan="7" style="text-align: right;">Total:</td>
    <td><%= @total %></td>
  </tr>
  </tfoot>
</table>
</div>
<div class="tab-footer clear no-print">
  <div class="fr">
    <%= paginate @bookings %>
  </div>
  <!--
  <div class="fl">
    <%= link_to "PDF", runsheet_path(request.parameters.symbolize_keys.merge({:format => :pdf})), :class => 'fl-space submit' %>
  </div>
  -->
</div>
<% end %>

app/views/reports/enrollments-pdf.html.erb
<div class="content-box">
  <div class="box-header clear">
    <h2>Enrollments</h2>
  </div>
  <div class="box-body clear">
    <div class="dataTables_wrapper">
      <% if @enrollments.empty? %>
          <div class="notification note-info">
            <span class="icon"></span>
            <p><strong>No enrollments:</strong> No enrollments found that match the filter criteria.</p>
          </div>
      <% else %>
          <table class="styled">
            <thead>
            <tr>
              <th width="1%">Booking</th>
              <th>Customer</th>
              <th>Email</th>
              <th>Phone</th>
            </tr>
            </thead>
            <tbody>
            <% @enrollments.each do |enrollment| %>
                <tr>
                  <td><%= enrollment.booking_id %></td>
                  <td><%= enrollment.name %></td>
                  <td><%= enrollment.email %></td>
                  <td><%= enrollment.phone %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/enrollments.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name=<%= "Enrollments" %>>
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Booking</Data></Cell>
        <Cell><Data ss:Type="String">Customer</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
      </Row>
      <% @enrollments.each do |enrollment| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= enrollment.booking_id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= enrollment.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= enrollment.email %></Data></Cell>
            <Cell><Data ss:Type="String"><%= enrollment.phone %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/reports/gantt.html.erb
<div class="content-box">
  <div class="box-header clear">
    <h2>Gantt</h2>
  </div>

  <div class="box-body clear">
    <div class="clear">
      <form action="/reports/gantt" method="get" class="no-print">
        <table class="styled">
          <caption>Filter</caption>
          <tbody>
          <tr>
            <td class="title"><label for="start">Date Range:</label></td>
            <td>
              <input type="text" id="start" name="start" class="datepicker" size="15"/>
              <label for="finish">-&nbsp;</label><input type="text" id="finish" name="finish" class="datepicker" size="15"/>
            </td>
          </tr>
          <tr>
            <td class="title"><label for="products">Product:</label></td>
            <td>
              <select id="products" name="products">
                <%= display_product_search_options %>
              </select>
              <label for="variants">/</label>
              <select id="variants" name="variants">
                <option value="">Select Variant...</option>
                <%= display_product_variants %>
              </select>
            </td>
          </tr>
          </tbody>
        </table>

        <div class="tab-footer">
          <div style="text-align:right">
            <input type="submit" class="submit" value="Search"/>
          </div>
        </div>
      </form>

      <div class="gantt_wrapper">
        <% if @bookings.empty? %>
            <div class="notification note-info">
              <span class="icon"></span>
              <p><strong>No bookings:</strong> No bookings found that match the filter criteria.</p>
            </div>
        <% else %>
            <div class="gantt" ></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :footer do -%>
    <%= javascript_include_tag 'reports-helper.js' %>

    <style>
        .gantt_wrapper .gantt {border: 1px solid #eee; margin:0}
    </style>

    <script>
        $('#start').datepicker('setDate', new Date('<%= @the_data.start %>'));
        $('#finish').datepicker('setDate', new Date('<%= @the_data.finish %>'));
        $('#products').val(<%= @the_data.product_id %>);
        $('#variants').val(<%= @the_data.variant_id %>);

        $("<link/>", { "rel": "stylesheet", "type": "text/css", "href": "http://taitems.github.io/jQuery.Gantt/css/style.css" }).appendTo("head");
        $.getScript("http://taitems.github.io/jQuery.Gantt/js/jquery.fn.gantt.js", main);

        // http://taitems.github.io/jQuery.Gantt/
        ganttData = [
            <% @bookings.each_with_index do |item, i| %>
            <% booking = item.booking %>
            {
                name: '<%= link_to booking.name, edit_booking_path(booking) %>',
//                desc: "Booking <%= booking.id %>",
                values: [
                    <% item.quantity.times do |x| %>
                    {
                        label: "Slot <%= x %>",
                        from: new Date('<%= item.start.strftime("%Y-%m-%d %H:%M:%S") %>'),
                        to: new Date('<%= item.finish.strftime("%Y-%m-%d %H:%M:%S") %>'),
                        customClass: "ganttRed"
                    }<% if x < item.quantity %>,<% end %>
                    <% end %>
                ]
            }<% if i < @bookings.size %>,<% end %>
            <% end %>
        ]

        function main(){
            $(".gantt").gantt({
                source: ganttData,
                scale: "days",
                minScale: "days",
                maxScale: "months",
                itemsPerPage: 50
            });
        }
    </script>
<% end %>

app/views/reports/runsheet.html.erb
<div class="content-box">
  <div class="box-header clear">
    <h2>Run Sheet</h2>
  </div>
  <div class="box-body clear">
    <div class="clear">
      <%= render "runsheet_filter" %>

      <div class="dataTables_wrapper">
        <% if @bookings.empty? %>
            <div class="notification note-info">
              <span class="icon"></span>
              <p><strong>No bookings:</strong> No bookings found matching the filter criteria.</p>
            </div>
        <% else %>
            <table class="styled">
              <thead>
              <tr>
                <th width="1%"><input type="checkbox" name="all_bookings" id="send_reminders_to_all"/></th>
                <th width="1%">Booking</th>
                <th width="1%">Order</th>
                <th width="1%">Date/Time</th>
                <th class="nowrap">Customer</th>
                <th>Products</th>
                <th width="1%">#</th>
                <th>Notes</th>
              </tr>
              </thead>
              <tbody>
              <% @bookings.each do |item| %>
                  <% booking = item.booking %>
                  <tr>
                    <td><%= check_box_tag "booking_ids[]", booking.id, false, class: 'bookings_ids' %></td>
                    <td>
                      <span class="nowrap">
                        <% if booking.is_a?(Booking) %>
                            <span class="no-print ui-icon <%= "#{booking.status == 2 ? 'ui-icon-calendar' : 'ui-icon-clock'}"%>" %> ></span>
                            <%= link_to booking.id, edit_booking_path(booking), title: booking.status == 2 ? 'Confirmed' : 'Reserved' %>
                        <% end %>
                      </span>
                    </td>
                    <td>
                      <% if booking.order_id.present? %>
                          <a href='<%= "https://#{current_shop.url}/admin/orders/#{booking.order_id}" %>' target='_blank'>
                            <span class="nowrap"><%= booking.order_name.nil? ? "View Order" : booking.order_name %></span>
                          </a>
                      <% end %>
                    </td>
                    <td>
                      <% if item.variant.all_day? %>
                          <span class="nowrap"><%= I18n.localize(item.start.to_date, :format => :short) %></span>
                          <% if item.start.to_date < item.finish.to_date %>
                              &nbsp;-&nbsp;<br/>
                              <span class="nowrap"><%= I18n.localize(item.finish.to_date, :format => :short) %></span>
                          <% end %>
                      <% else %>
                          <span class="nowrap"><%= I18n.localize(item.start, :format => :short) %>&nbsp;-&nbsp;</span><br/>
                          <span class="nowrap"><%= I18n.localize(item.finish, :format => :short) %></span>
                      <% end %>
                    </td>
                    <td>
                      <span class="nowrap">
                        <span class="no-print ui-icon ui-icon-mail-closed"></span>
                        <%= mail_to booking.email, booking.name, :subject => booking.product_summary %>
                      </span>
                      <% unless booking.phone.blank? %>
                      <br/>
                      <span class="nowrap">
                        <span class="no-print ui-icon ui-icon-contact"></span>
                        <a href="tel:<%= booking.phone %>"><%= booking.phone %></a>
                      </span>
                      <% end %>
                    </td>
                    <td>
                      <%= "#{item.product.product_title}/#{item.variant.title}" %>
                    </td>
                    <td><%= item.quantity %></td>
                    <td><%= booking.notes %></td>
                  </tr>
              <% end %>
              </tbody>
              <tfoot>
              <!--
                <tr>
                  <td colspan="7" style="text-align: right;">Page total:</td>
                  <td><%= @total %></td>
                  <td></td>
                </tr>
                -->
              <tr>
                <td colspan="6" style="text-align: right;">Total:</td>
                <td><%= @total %></td>
                <td></td>
              </tr>
              </tfoot>
            </table>
            <div class="tab-footer clear no-print">
              <div class="fr">
                <%= paginate @bookings %>
              </div>
              <div class="fl" style="width:100%">
                <a href="#" onClick="window.print(); return false;" class="fl-space submit">Print Page</a>
                <%= link_to "PDF", runsheet_path(request.parameters.merge({:format => "pdf"})), :class => 'fl-space submit' %>
                <!-- <%= link_to "CSV", runsheet_path(request.parameters.merge({:format => "csv"})), :class => 'fl-space submit' %> -->
                <%= link_to "Excel", runsheet_path(request.parameters.merge({:format => "xls"})), :class => 'fl-space submit' %>
                <%= render "common/reminder_widget" %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :footer do %>
    <script>
        $('#start').datepicker('setDate', new Date('<%= @the_data.start %>'));
        $('#finish').datepicker('setDate', new Date('<%= @the_data.finish %>'));

        $(document).ready(function () {
            $('#date_type').val('<%= @the_data.date_type %>');
        });

        btaa.reminderBookingIds = function() {
          return $('.bookings_ids:checked').map(function () {
            return this.value;
          }).get();
        };

        $('#send_reminders_to_all').click(function() {
          if (this.checked) {
            $('.bookings_ids').prop('checked', true);
          } else {
            $('.bookings_ids').prop('checked', false);
          }
        });
    </script>
<% end %>